name: Sync develop to release and build

on:
  push:
    branches:
      - develop

jobs:
  validate-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Frontend
      run: npm run build

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Sync develop to release
      if: success()
      run: |
        git checkout release || git checkout --orphan release
        git push origin release --force
